### PR TITLE
FAQ fix

### PR DESCRIPTION
**Pull request by m1ga**
fix for FAQ translations

BTW:
https://en.wikipedia.org/wiki/Sidecar_file -> https://de.wikipedia.org/wiki/Filialdatei
never heard that word before :smile: But it looks like to be the correct term (instead of "Beiwagen" which is wrong in this case)

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you for checking :) ! 
I oversaw this one. "Beiwagen" is as good as "Trinkgeld" for tip :D

**Comment by m1ga** [comment]
True, but I have to say that Google does quiet a good job in translating everything.

**Comment by graciousgrey** [comment]
Yes, in some sentences you don't see that it was translated by Google. 
In your opinion what is easier to understand for germans "Filialdateien" or something like "Sidecar-Dateien"? I am a bit biased because I am used to the term sidecar.

**Comment by m1ga** [comment]
looking around I think it would be better to use "Sidecar Dateien" like you've suggested. Other tools seems to use that term too.

**Pull request merged**
