### PR TITLE
Translated to German

### PR DESCRIPTION
**Pull request by bhavesh1129**
**_I had translated the following files into the German language:_**

- docs/user-guide/settings/account.md

- docs/user-guide/settings/library.md

- docs/user-guide/settings/places.md

- docs/user-guide/settings/thumbnails.md

- docs/user-guide/settings/ui.md

### CODE REVIEW

**Comment by m1ga** [comment]
That looks like a automatic translation. Some stuff doesn't make sense :man_shrugging:

**Comment by bhavesh1129** [comment]
> That looks like a automatic translation. Some stuff doesn't make sense 🤷‍♂️

Yes Actually I had translated through Google Translator

**Comment by m1ga** [comment]
but why? It is not useful for the project if it is a wrong translation. Most stuff is correct but it doesn't sound good.

**Comment by bhavesh1129** [comment]
> but why? It is not useful for the project if it is a wrong translation. Most stuff is correct but it doesn't sound good.

Yeah, I see that!

**Comment by graciousgrey** [comment]
Unfortunately this pull request is not useful. The text was just put into Google Translate. And icons + formatting are broken as well. I will update the ticket description to communicate our quality standards more  clearly.

**Pull request closed without merging**
